const types = {
    OPEN_COOKBOOKS: "OPEN_COOKBOOKS",
    OPEN_RECIPES: "OPEN_RECIPES",
    OPEN_EDIT: "OPEN_EDIT",
    OPEN_CONTENT_COOKBOOKS: "OPEN_CONTENT_COOKBOOKS",
    OPEN_CONTENT_RECIPES: "OPEN_CONTENT_RECIPES"
}

export default types;