const types = {
    ADD_COOKBOOK_USERNAME: "ADD_COOKBOOK_USERNAME",
    ADD_COOKBOOK_TITLE: "ADD_COOKBOOK_TITLE",
    ADD_COOKBOOK_IMAGE: "ADD_COOKBOOK_IMAGE",
    ADD_COOKBOOK_DESCRIPTION: "ADD_COOKBOOK_DESCRIPTION",
    ADD_RECIPE: "ADD_RECIPE",
    DELETE_RECIPE: "DELETE_RECIPE",
    RESET_COOKBOOK_DATA: "RESET_COOKBOOK_DATA"
}

export default types;