const types = {
    FETCH_USER_DATA_START: "FETCH_USER_DATA_START",
    FETCH_USER_DATA_FAIL: "FETCH_USER_DATA_FAIL",
    FETCH_USER_DATA_SUCCESS: "FETCH_USER_DATA_SUCCESS",
    UPDATE_USER_AVATAR_START: "UPDATE_USER_AVATAR",
    UPDATE_USER_AVATAR_FAIL: "UPDATE_USER_AVATAR_FAIL",
    UPDATE_USER_AVATAR_SUCCESS: "UPDATE_USER_AVATAR_SUCCESS",
    UPDATE_USER_NAME_START: "UPDATE_USER_NAME_START",
    UPDATE_USER_NAME_FAIL: "UPDATE_USER_NAME_FAIL",
    UPDATE_USER_NAME_SUCCESS: "UPDATE_USER_NAME_SUCCESS",
    UPDATE_USER_EMAIL_START: "UPDATE_USER_EMAIL_START",
    UPDATE_USER_EMAIL_FAIL: "UPDATE_USER_EMAIL_FAIL",
    UPDATE_USER_EMAIL_SUCCESS: "UPDATE_USER_EMAIL_SUCCESS",
    UPDATE_USER_PASSWORD_START: "UPDATE_USER_PASSWORD_START",
    UPDATE_USER_PASSWORD_FAIL: "UPDATE_USER_PASSWORD_FAIL",
    UPDATE_USER_PASSWORD_SUCCESS: "UPDATE_USER_PASSWORD_SUCCESS"
}

export default types;