const types = {
    FETCH_USER_DATA_START: "FETCH_USER_DATA_START",
    FETCH_USER_DATA_FAIL: "FETCH_USER_DATA_FAIL",
    FETCH_USER_DATA_SUCCESS: "FETCH_USER_DATA_SUCCESS",
    UPDATE_USER_AVATAR_START: "UPDATE_USER_AVATAR",
    UPDATE_USER_AVATAR_FAIL: "UPDATE_USER_AVATAR_FAIL",
    UPDATE_USER_AVATAR_SUCCESS: "UPDATE_USER_AVATAR_SUCCESS"
}

export default types;