const types = {
    ADD_INGREDIENT: "ADD_INGREDIENT",
    DELETE_INGREDIENT: "DELETE_INGREDIENT",
    ADD_RECIPE_TITLE: "ADD_RECIPE_TITLE",
    ADD_RECIPE_IMAGE: "ADD_RECIPE_IMAGE",
    ADD_RECIPE_DESCRIPTION: "ADD_RECIPE_DESCRIPTION",
    ADD_RECIPE_DIRECTIONS: "ADD_RECIPE_DIRECTIONS",
    ADD_RECIPE_USERNAME: "ADD_RECIPE_USERNAME",
    RESET_RECIPE_DATA: "RESET_RECIPE_DATA"
}

export default types;