const types = {
    FETCH_USER_RECIPES_START: "FETCH_USER_RECIPES_START",
    FETCH_USER_RECIPES_SUCCESS: "FETCH_USER_RECIPES_SUCCESS",
    FETCH_USER_RECIPES_FAIL: "FETCH_USER_RECIPES_FAIL",
    FETCH_USER_COOKBOOKS_START: "FETCH_USER_COOKBOOKS_START",
    FETCH_USER_COOKBOOKS_SUCCESS: "FETCH_USER_COOKBOOKS_SUCCESS",
    FETCH_USER_COOKBOOKS_FAIL: "FETCH_USER_COOKBOOKS_FAIL",
    FETCH_RECIPES_START: "FETCH_DATA_START",
    FETCH_RECIPES_SUCCESS: "FETCH_RECIPES_SUCCESS",
    FETCH_RECIPES_FAIL: "FETCH_RECIPES_FAIL",
    FETCH_COOKBOOKS_START: "FETCH_COOKBOOKS_START",
    FETCH_COOKBOOKS_SUCCESS: "FETCH_COOKBOOKS_SUCCESS",
    FETCH_COOKBOOKS_FAIL: "FETCH_COOKBOOKS_FAIL",
    SORT_RECIPES_BY_VIEWS: "SORT_RECIPES_BY_VIEWS",
    SORT_RECIPES_BY_LIKES: "SORT_RECIPES_BY_LIKES",
    SORT_COOKBOOKS_BY_VIEWS: "SORT_COOKBOOKS_BY_VIEWS",
    SORT_COOKBOOKS_BY_LIKES: "SORT_COOKBOOKS_BY_LIKES"
}

export default types;