const types = {
    FETCH_USER_RECIPES_START: "FETCH_USER_RECIPES_START",
    FETCH_USER_RECIPES_SUCCESS: "FETCH_USER_RECIPES_SUCCESS",
    FETCH_USER_RECIPES_FAIL: "FETCH_USER_RECIPES_FAIL",
    FETCH_USER_COOKBOOKS_START: "FETCH_USER_COOKBOOKS_START",
    FETCH_USER_COOKBOOKS_SUCCESS: "FETCH_USER_COOKBOOKS_SUCCESS",
    FETCH_USER_COOKBOOKS_FAIL: "FETCH_USER_COOKBOOKS_FAIL"
}

export default types;