const types = {
    START_RECIPE_UPLOAD: "START_DATA_UPLOAD",
    RECIPE_UPLOAD_SUCCESS: "RECIPE_UPLOAD_SUCCESS",
    RECIPE_UPLOAD_FAIL: "RECIPE_UPLOAD_FAIL",
    START_COOKBOOK_UPLOAD: "START_COOKBOOK_UPLOAD",
    COOKBOOK_UPLOAD_SUCCESS: "COOKBOOK_UPLOAD_SUCCESS",
    COOKBOOK_UPLOAD_FAIL: "COOKBOOK_UPLOAD_FAIL"
}

export default types;