const types = {
    SELECT_RECIPE_IMAGE: "SELECT_RECIPE_IMAGE",
    START_IMAGE_UPLOAD: "START_IMAGE_UPLOAD",
    IMAGE_UPLOAD_SUCCESS: "IMAGE_UPLOAD_SUCCESS",
    IMAGE_UPLOAD_FAIL: "IMAGE_UPLOAD_FAIL",
    RESET_IMAGE_DATA: "RESET_IMAGE_DATA"
}

export default types;