const types = {
    UPDATE_RECIPE_VIEWS_START: "UPDATE_RECIPE_VIEWS_START",
    UPDATE_RECIPE_VIEWS_SUCCESS: "UPDATE_RECIPE_VIEWS_SUCCESS",
    UPDATE_RECIPE_VIEWS_FAIL: "UPDATE_RECIPE_VIEWS_FAIL",
    UPDATE_COOKBOOK_VIEWS_START: "UPDATE_COOKBOOK_VIEWS_START",
    UPDATE_COOKBOOK_VIEWS_SUCCESS: "UPDATE_COOKBOOK_VIEWS_SUCCESS",
    UPDATE_COOKBOOK_VIEWS_FAIL: "UPDATE_COOKBOOK_VIEWS_FAIL"
}

export default types;